baseurl = "https://theoriginalminifilia.blog/"
languageCode = "en-us"
title = "The Life and Times of Mini Filia"
theme = "internet-weblog"
Paginate = 10
SectionPagesMenu = "main"

[author]
   Handle = "Mini Filia"
   FirstName = "Mini"
   LastName = "Filia"
   AboutPage = "/about"
   Location = "Old Sharlayan, The Northern Empty"
   FlickrID = ""

[params]
   Description = "This is my blog, read it and enjoy."
   ShowCopyright = true
   EnablePreferredDarkAppearance = true
   RSSEnabled = true
   RSSSections = [ "Posts", "Microposts", "Photos" ]

[taxonomies]
   tag = "tags"
   category = "categories"
   series = "series"

[[menu.main]]
   name = "Posts"
   weight = 2
   identifier = "posts"
   url = "/posts/"

[[menu.main]]
   name = "Microposts"
   weight = 3
   identifier = "microposts"
   url = "/microposts/"

[[menu.main]]
   name = "Photos"
   weight = 4
   identifier = "photos"
   url = "/photos/"

  [[menu.main]]
   name = "Home"
   weight = 1
   identifier = "Home"
   url = "https://www.theoriginalminifilia.com"
   